version: '3.8'

services:
  rundown-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - PORT=5000
    env_file:
      - .env
    volumes:
      - ./tokens:/app/tokens
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - rundown-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/auth/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Redis for session storage (if you want to scale horizontally)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - rundown-network
    command: redis-server --appendonly yes

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - rundown-app
    restart: unless-stopped
    networks:
      - rundown-network

networks:
  rundown-network:
    driver: bridge

volumes:
  redis_data:
