services:
  - type: web
    name: sefa
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: PRODUCTION
        value: "true"
      - key: CLIENT_SECRET
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: SECRET_KEY
        sync: false 