services:
  - type: web
    name: rundown
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: OAUTH_REDIRECT_URI
        value: https://rundown.onrender.com/oauth/callback
      - key: GOOGLE_CREDENTIALS
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: SECRET_KEY
        sync: false 